<a href="https://colab.research.google.com/github/RuthKassahun/ML-with-Scikit/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding "Country" and "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
lableencoder_x_1 = LabelEncoder()
X[:, 1] = lableencoder_x_1.fit_transform(X[:, 1])

In [ ]:
print(X)

[[619 0 'Female' ... 1 1 101348.88]
 [608 2 'Female' ... 0 1 112542.58]
 [502 0 'Female' ... 1 0 113931.57]
 ...
 [709 0 'Female' ... 0 1 42085.58]
 [772 1 'Male' ... 1 0 92888.52]
 [792 0 'Female' ... 1 0 38190.78]]


In [ ]:
lableencoder_x_2= LabelEncoder()
X[:, 2] = lableencoder_x_2.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
X = X[:,1:]

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier = Sequential()

first layer

In [ ]:
classifier.add(Dense(6, kernel_initializer='uniform',activation='relu', input_dim=11))


For second hidden layer

In [ ]:
classifier.add(Dense(6, kernel_initializer='uniform',activation='relu'))


In [ ]:
classifier.add(Dense(1, kernel_initializer='uniform',activation='sigmoid'))


In [ ]:
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'] )

In [ ]:
classifier.fit(X_train,y_train, batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4892 - accuracy: 0.7958
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4239 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4199 - accuracy: 0.8120
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4171 - accuracy: 0.8230
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4152 - accuracy: 0.8290
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4134 - accuracy: 0.8314
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4118 - accuracy: 0.8319
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4103 - accuracy: 0.8316
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4092 - accura

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
y_pred = (y_pred>0.5)

In [ ]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

In [ ]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
new_prediction =(new_prediction>0.5)
print(new_prediction)


[[False]]


Apply k-fold cross validation

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(6, kernel_initializer='uniform',activation='relu', input_dim=11))
  classifier.add(Dense(6, kernel_initializer='uniform',activation='relu'))
  classifier.add(Dense(1, kernel_initializer='uniform',activation='sigmoid'))
  classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'] )
  return classifier

classifier = KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=20)

accuracies = cross_val_score(estimator=classifier, X = X_train, y= y_train,cv=10,n_jobs=-1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  if __name__ == '__main__':


In [ ]:
mean = accuracies.mean()
variance = accuracies.std()

print(mean)
print(variance)

0.8357499957084655
0.016048759060132804


dropout is used to disable some of the neurons to avoid overfitting


In [ ]:
from keras.layers import Dropout

In [ ]:

classifier.add(Dense(6, kernel_initializer='uniform',activation='relu', input_dim=11))
classifier.add(Dropout(p=0.1))
classifier.add(Dense(6, kernel_initializer='uniform',activation='relu'))
classifier.add(Dropout(p=0.1))
classifier.add(Dense(1, kernel_initializer='uniform',activation='sigmoid'))
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'] )
 

Instead of using cross_val k folds of traning, we can use grid search to find the best hyper parametes to tune our neural network

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(6, kernel_initializer='uniform',activation='relu', input_dim=11))
  classifier.add(Dense(6, kernel_initializer='uniform',activation='relu'))
  classifier.add(Dense(1, kernel_initializer='uniform',activation='sigmoid'))
  classifier.compile(optimizer=optimizer,loss='binary_crossentropy', metrics=['accuracy'] )
  return classifier

classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size':[25,32], 
              'epochs':[100,500],
              'optimizer':['adam','rmsprop']}

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters,scoring='accuracy',cv=10)
grid_search = grid_search.fit(X_train,y_train)

best_parameters =grid_search.best_params_
best_accuracy = grid_search.best_score_


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  if __name__ == '__main__':


Streaming output truncated to the last 5000 lines.
225/225 [==============================] - 1s 2ms/step - loss: 0.4019 - accuracy: 0.8338
Epoch 344/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4016 - accuracy: 0.8363
Epoch 345/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4020 - accuracy: 0.8338
Epoch 346/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4021 - accuracy: 0.8333
Epoch 347/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4022 - accuracy: 0.8336
Epoch 348/500
225/225 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8344
Epoch 349/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4020 - accuracy: 0.8346
Epoch 350/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4020 - accuracy: 0.8338
Epoch 351/500
225/225 [==============================] - 1s 3ms/step - loss: 0.4022 - accuracy: 0.8360
Epoch 352/500
225/225 [=============