<a href="https://colab.research.google.com/github/RuthKassahun/ML-with-Scikit/blob/main/digit_recongnition_with_K_fold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [ ]:
print(digits)

In [13]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [ ]:
ir = LogisticRegression()
ir.fit(x_train,y_train)
ir.score(x_test,y_test)

In [15]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [16]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9740740740740741

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [24]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
  print(train_index,test_index)


[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [26]:
def get_score (model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [ ]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)


In [ ]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

In [31]:
folds = StratifiedKFold(n_splits=3)

In [ ]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

In [ ]:
scores_l = []
scores_svm= []
scores_rf =[]

for train_index,test_index in kf.split(digits.data):
  x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
  scores_l.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  scores_l.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))